<a href="https://colab.research.google.com/github/Vedu2510/CodeClauseInternship_SalesPredictor/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy


In [2]:
import numpy as np


In [3]:
list=[1,2,3,4]

In [4]:
type(list)

list

In [5]:
arr=np.array(list)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)


numpy.ndarray

In [8]:
1
2
3
4

4

In [9]:
arr.size

4

In [10]:
z=np.zeros(10)

In [11]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#one dimensional array
o=np.array([1,2,3,4])

In [13]:
o

array([1, 2, 3, 4])

In [14]:
o.ndim

1

In [15]:
o.shape

(4,)

In [16]:
#2-d array
x=np.array([[1,2,3],[4,5,6],[7,8,9],[4,9,6]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 9, 6]])

In [17]:
x.ndim

2

In [18]:
x.shape

(4, 3)

In [19]:
#3 d array
x=x.reshape(3,2,2)
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 4],
        [9, 6]]])

In [20]:
x.ndim

3

In [21]:
x.shape

(3, 2, 2)

In [22]:
x=x.reshape(3,4)

In [23]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 4, 9, 6]])

In [24]:
x.ndim

2

In [25]:
x.shape

(3, 4)

INDEXING

ACCESSING 1D ARRAY

In [26]:
arr=np.array([1,2,3,4])

In [27]:
arr[1]

2

In [28]:
arr[1]+arr[2]

5

Accessing 2d array

In [29]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [30]:
print("2 element in 1 st dim",arr[0,1])

2 element in 1 st dim 2


In [31]:
print("2 element in 2 st dim",arr[1,1])

2 element in 2 st dim 7


In [32]:
print("5 element in 2 st dim",arr[1,4])

5 element in 2 st dim 10


In [33]:
#linspace linspace(start,end,no of values between 0 and 10)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
#identitiy matrix
x=np.eye(3)

In [36]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
x.shape

(3, 3)

In [38]:
np.random.randint(0,50,20)

array([27, 38,  5, 45, 46,  8, 28, 41, 48, 22, 21,  7,  4, 17, 33, 21,  8,
       18,  8, 33])

In [39]:
np.random.rand(3,3)

array([[0.3761067 , 0.03478107, 0.79132323],
       [0.37324856, 0.82650748, 0.81202989],
       [0.84718626, 0.07416675, 0.84553128]])

In [40]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [42]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
arr.max()

10

In [44]:
arr.argmax()

9

In [45]:
arr.min()

1

In [46]:
a=np.arange(0,11,2)

slicing

In [47]:
a

array([ 0,  2,  4,  6,  8, 10])

In [48]:
a[1:3]   #[start value:end value+1]

array([2, 4])

In [49]:
a=np.array([[1,2,3],[2,3,4],[4,5,6]])

In [50]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [51]:
a[0:0+1,0:1+1]

array([[1, 2]])

In [52]:
a[0:1,0:2]

array([[1, 2]])

In [53]:
a[0:1,1:3]

array([[2, 3]])

In [ ]:
array([[1, 2, 3],    1 st row   0
       [2, 3, 4],    2 nd row   1
       [4, 5, 6]])    3 rd row  2

       c1  c2 c3

In [58]:
a[2:3,0:2]

array([[4, 5]])

In [59]:
a[0:2,1:3]

array([[2, 3],
       [3, 4]])

In [60]:
a[1:3,1:3]

array([[3, 4],
       [5, 6]])

In [61]:
a[1:,1:]

array([[3, 4],
       [5, 6]])

In [62]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [63]:
a=np.arange(0,11,2)

In [64]:
a

array([ 0,  2,  4,  6,  8, 10])

In [65]:
a1=np.arange(0,11,2)

In [66]:
c=a+a1

In [67]:
c

array([ 0,  4,  8, 12, 16, 20])

In [68]:
np.sqrt(c)

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595])

In [69]:
np.sin(c)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332,
        0.91294525])

In [70]:
arr=np.array([1,2,3,4,5])
x=arr.copy()

In [71]:
arr

array([1, 2, 3, 4, 5])

In [72]:
x

array([1, 2, 3, 4, 5])

In [73]:
arr[0]=31

In [74]:
arr

array([31,  2,  3,  4,  5])

In [75]:
x

array([1, 2, 3, 4, 5])

In [76]:
z=arr.view()

In [77]:
z

array([31,  2,  3,  4,  5])

In [78]:
arr[1]=45

In [79]:
arr

array([31, 45,  3,  4,  5])

In [80]:
z

array([31, 45,  3,  4,  5])

In [ ]:
create an array 5 *5 whcih should contain from 0 to 24